### ISSUE TITLE
NX30 Connections files

### ISSUE THREAD

**Issue by hunkreborn** [ajavamind/Multi-NX-Camera-Control#1]
Hi! I've been trying to use it with my NX30, but the app is trying to connect to 192.168.1.25, my lan is at 192.168.101.10-200, NX30 is using 192.168.101.159 right now, is there a model of the configuration file that I can edit?
Thanks!

**Comment by ajavamind** [comment]
Hi Gustavo, 
Create a text file with a single line as follows - similar to file cameraNX300.txt in the data folder:
192.168.101.159 Main NX300 0

I chose NX300 camera type since it was introduced a month before the NX30. See https://cameradecision.com/compare/Samsung-NX300-vs-Samsung-NX30

The NX300 use a telnet prompt of "nx300:/# " and I believe the NX30 camera telnet will use "nx30:/# "
This will cause MultiNX app to think the camera is not connected.  Please check what prompt comes back from telnet.
I will be making an update to MultiNX to add more cameras and will add NX30 with guess about how it works, since I did not have a NX30 camera for testing. **The location of camera data may have changed in the NX30 and I will need to know from you what the NX30 uses.**

Because you had problems starting telnet, previously, I would try this autoexec.sh file in your sd card:

```
#!/bin/sh
# Samsung NX500 startup script
# wait for WiFi connection
#sleep 30
mkdir -p /dev/pts
mount -t devpts none /dev/pts
# Telnet server
/mnt/mmc/telnetd &
# HTTP server
/mnt/mmc/busybox httpd -h /mnt/mmc
# FTP server
/mnt/mmc/busybox tcpsvd -u root -vE 0.0.0.0 21 /mnt/mmc/busybox ftpd -w /mnt/mmc &
#killall dfmsd
```

I removed the sleep line and killall dfmsd used by NX500 autoexec.sh

And you should try sdcard without the files info.tg and nx_cs.adj because I think autoexec.sh may start without them.

Thanks

**Comment by ajavamind** [comment]
No NX30 available for testing
